# Generated by Django 5.1.6 on 2025-03-01 15:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "message",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="text"),
                ),
                ("image", models.ImageField(upload_to="newsletter/")),
                ("sent_at", models.DateTimeField(auto_now=True)),
                ("sent", models.BooleanField(default=False)),
                ("recipients", models.ManyToManyField(to="newsletter.subscriber")),
            ],
        ),
    ]
