# Generated by Django 5.1.6 on 2025-03-01 16:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="message",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
