# Generated by Django 5.1.6 on 2025-03-21 15:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsdArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Heart Diseases', 'Heart Diseases'), ('Vascular Diseases', 'Vascular Diseases'), ('Systemic Diseases', 'Systemic Diseases')], max_length=50)),
                ('sub_category', models.CharField(choices=[('Congenital Heart Diseases', 'Congenital Heart Diseases'), ('Valvular Heart Diseases', 'Valvular Heart Diseases'), ('Myocardial Diseases', 'Myocardial Diseases'), ('Ischemic Heart Diseases', 'Ischemic Heart Diseases'), ('Thromboembolic Diseases', 'Thromboembolic Diseases'), ('Arrhythmias', 'Arrhythmias'), ('Hypertensive Heart Disease', 'Hypertensive Heart Disease'), ('Heart Failure', 'Heart Failure'), ('Pericardial Diseases', 'Pericardial Diseases'), ('Metabolic Disorders', 'Metabolic Disorders'), ('Arterial Diseases', 'Arterial Diseases'), ('Venous Diseases', 'Venous Diseases')], max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('keywords', models.CharField(help_text='comma-separated keywords', max_length=500)),
                ('search_queries', models.CharField(help_text='csv', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_image', models.ImageField(upload_to='S&D/primary_images')),
                ('video_URL', models.URLField(blank=True, null=True)),
                ('links', models.TextField(blank=True, help_text='enter multiple URLs as csv', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='S&D/attached_files')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='cardiacSymptomsAndDiagnosis.csdarticle')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='S&D/secondary_images')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_images', to='cardiacSymptomsAndDiagnosis.csdarticle')),
            ],
        ),
    ]
