# Generated by Django 5.1.6 on 2025-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacSymptomsAndDiagnosis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachedfile",
            name="attached_file",
            field=models.FileField(
                blank=True, null=True, upload_to="S&D/attached_files"
            ),
        ),
        migrations.AlterField(
            model_name="secondaryimage",
            name="secondary_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="S&D/secondary_images"
            ),
        ),
    ]
