# Generated by Django 5.1.6 on 2025-02-26 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cardiacSymptomsAndDiagnosis",
            "0002_alter_attachedfile_attached_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_highlighted_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
