# Generated by Django 5.1.6 on 2025-03-21 23:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacSymptomsAndDiagnosis', '0002_alter_csdarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdarticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
