# Generated by Django 5.1.6 on 2025-03-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacSymptomsAndDiagnosis', '0003_alter_csdarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdarticle',
            name='sub_category',
            field=models.CharField(choices=[('Congenital Heart Diseases', 'Congenital Heart Diseases'), ('Valvular Heart Diseases', 'Valvular Heart Diseases'), ('Myocardial Diseases', 'Myocardial Diseases'), ('Ischemic Heart Diseases', 'Ischemic Heart Diseases'), ('Thromboembolic Diseases', 'Thromboembolic Diseases'), ('Arrhythmias', 'Arrhythmias'), ('Hypertensive Heart Diseases', 'Hypertensive Heart Diseases'), ('Heart Failure', 'Heart Failure'), ('Pericardial Diseases', 'Pericardial Diseases'), ('Metabolic Disorders', 'Metabolic Disorders'), ('Arterial Diseases', 'Arterial Diseases'), ('Venous Diseases', 'Venous Diseases')], max_length=50, null=True),
        ),
    ]
