# Generated by Django 5.1.6 on 2025-02-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacSymptomsAndDiagnosis", "0011_alter_article_is_highlighted_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="primary_image",
            field=models.ImageField(upload_to="S&D/primary_images"),
        ),
    ]
