# Generated by Django 5.1.6 on 2025-02-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacSymptomsAndDiagnosis", "0012_alter_article_primary_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
