# Generated by Django 5.1.6 on 2025-02-28 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacSymptomsAndDiagnosis", "0014_article_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="CsdArticle",
        ),
    ]
