# Generated by Django 5.1.6 on 2025-02-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacSymptomsAndDiagnosis", "0015_rename_article_csdarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="csdarticle",
            name="search_queries",
            field=models.CharField(help_text="csv", max_length=200, null=True),
        ),
    ]
