# Generated by Django 5.1.6 on 2025-03-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacSymptomsAndDiagnosis', '0018_alter_csdarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdarticle',
            name='category',
            field=models.CharField(choices=[('heart diseases', 'Heart diseases'), ('vascular diseases', 'Vascular diseases'), ('systemic & Inflammatory Cardiovascular Diseases', 'Systemic & Inflammatory Cardiovascular Diseases')], max_length=50),
        ),
    ]
