# Generated by Django 5.1.6 on 2025-03-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacSymptomsAndDiagnosis', '0019_alter_csdarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdarticle',
            name='category',
            field=models.CharField(choices=[('heart diseases', 'Heart diseases'), ('vascular diseases', 'Vascular diseases'), ('Systemic Diseases', 'Systemic Diseases')], max_length=50),
        ),
    ]
