# Generated by Django 5.1.6 on 2025-03-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacSymptomsAndDiagnosis', '0020_alter_csdarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdarticle',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
