# Generated by Django 5.1.6 on 2025-03-21 15:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CwbArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Stress', 'Stress Management'), ('Exercice', 'Physical Activity'), ('Nutrition', 'Nutrition & Diet'), ('MindBody', 'Mind-Body Practices')], max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('overView', models.TextField()),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('keywords', models.CharField(help_text='comma-separated keywords', max_length=500)),
                ('search_queries', models.CharField(help_text='csv', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_image', models.ImageField(upload_to='CWB/primary_images')),
                ('video_URL', models.URLField(blank=True, null=True)),
                ('links', models.TextField(blank=True, help_text='enter multiple URLs as csv', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='CWB/attached_files')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='cardiacWellBeing.cwbarticle')),
            ],
        ),
    ]
