# Generated by Django 5.1.6 on 2025-03-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacWellBeing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwbarticle',
            name='overView',
        ),
    ]
