# Generated by Django 5.1.6 on 2025-02-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacWellBeing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CwbAttachedFiles',
            new_name='CwbAttachedFile',
        ),
        migrations.RenameModel(
            old_name='CwbCategory',
            new_name='CwbCategorie',
        ),
        migrations.RenameModel(
            old_name='CwbSecondaryImages',
            new_name='CwbSecondaryImage',
        ),
    ]
