# Generated by Django 5.1.6 on 2025-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacWellBeing', '0002_rename_cwbattachedfiles_cwbattachedfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwbarticletag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='cwbarticletag',
            name='tag',
        ),
        migrations.AddField(
            model_name='cwbarticle',
            name='category',
            field=models.CharField(choices=[('wellness', 'wellness'), ('prevention', 'prevention')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CwbArticleCategory',
        ),
        migrations.DeleteModel(
            name='CwbCategorie',
        ),
        migrations.DeleteModel(
            name='CwbArticleTag',
        ),
        migrations.DeleteModel(
            name='CwbTag',
        ),
    ]
