# Generated by Django 5.1.6 on 2025-03-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacWellBeing', '0002_remove_cwbarticle_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwbarticle',
            name='content',
            field=models.TextField(),
        ),
    ]
