# Generated by Django 5.1.6 on 2025-02-26 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacWellBeing", "0004_rename_cwbarticle_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_highlighted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="is_highlighted_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
