# Generated by Django 5.1.6 on 2025-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cardiacWellBeing",
            "0005_article_is_highlighted_article_is_highlighted_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(default="Abdelmoughit Fikri", max_length=50),
        ),
    ]
