# Generated by Django 5.1.6 on 2025-02-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacWellBeing", "0009_alter_article_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="author",
            new_name="author_id",
        ),
    ]
