# Generated by Django 5.1.6 on 2025-02-26 19:44

import cardiacWellBeing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacWellBeing", "0011_rename_author_id_article_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                default=cardiacWellBeing.models.get_default_user,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="cardiacWellBeingArticles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
