# Generated by Django 5.1.6 on 2025-02-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacWellBeing", "0013_alter_article_is_highlighted_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="primary_image",
            field=models.ImageField(upload_to="CWB/primary_images"),
        ),
        migrations.AlterField(
            model_name="attachedfile",
            name="attached_file",
            field=models.FileField(
                blank=True, null=True, upload_to="CWB/attached_files"
            ),
        ),
        migrations.AlterField(
            model_name="secondaryimage",
            name="secondary_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="CWB/secondary_images"
            ),
        ),
    ]
