# Generated by Django 5.1.6 on 2025-02-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacWellBeing", "0015_article_author_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="links",
            field=models.TextField(
                blank=True, help_text="enter multiple URLs as csv", null=True
            ),
        ),
    ]
