openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /cardiac-diseases/:
    get:
      operationId: cardiac_diseases_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - cardiac-diseases
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCwbSRZList'
          description: ''
  /cardiac-diseases/{id}/:
    get:
      operationId: cardiac_diseases_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this article.
        required: true
      tags:
      - cardiac-diseases
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CwbSRZ'
          description: ''
components:
  schemas:
    AttachedFilesSRZ:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        attached_file:
          type: string
          format: uri
          nullable: true
        Article:
          type: integer
      required:
      - Article
      - id
    CwbSRZ:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        secondary_images:
          type: array
          items:
            $ref: '#/components/schemas/SecondaryImagesSRZ'
          readOnly: true
        attached_files:
          type: array
          items:
            $ref: '#/components/schemas/AttachedFilesSRZ'
          readOnly: true
        title:
          type: string
          maxLength: 200
        author:
          type: string
          maxLength: 50
        supra_category:
          $ref: '#/components/schemas/SupraCategoryEnum'
        sub_category:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/SubCategoryEnum'
          - $ref: '#/components/schemas/NullEnum'
        overView:
          type: string
        content:
          type: string
        keywords:
          type: string
          description: comma-separated keywords
          maxLength: 500
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        primary_image:
          type: string
          format: uri
        video_URL:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        is_active:
          type: boolean
      required:
      - attached_files
      - author
      - content
      - created_at
      - id
      - keywords
      - overView
      - primary_image
      - secondary_images
      - supra_category
      - title
      - updated_at
    NullEnum:
      enum:
      - null
    PaginatedCwbSRZList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/CwbSRZ'
    SecondaryImagesSRZ:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        secondary_image:
          type: string
          format: uri
          nullable: true
        Article:
          type: integer
      required:
      - Article
      - id
    SubCategoryEnum:
      enum:
      - Congenital Heart Diseases
      - Valvular Heart Diseases
      - Myocardial Diseases
      - Ischemic Heart Diseases
      - Electrical Disorders
      - Hypertensive Heart Disease
      - Heart Failure
      - Pericardial Diseases
      - Arterial Diseases
      - Venous Diseases
      type: string
      description: |-
        * `Congenital Heart Diseases` - Congenital Heart Diseases
        * `Valvular Heart Diseases` - Valvular Heart Diseases
        * `Myocardial Diseases` - Myocardial Diseases
        * `Ischemic Heart Diseases` - Ischemic Heart Diseases
        * `Electrical Disorders` - Electrical Disorders
        * `Hypertensive Heart Disease` - Hypertensive Heart Disease
        * `Heart Failure` - Heart Failure
        * `Pericardial Diseases` - Pericardial Diseases
        * `Arterial Diseases` - Arterial Diseases
        * `Venous Diseases` - Venous Diseases
    SupraCategoryEnum:
      enum:
      - heart diseases
      - vascular diseases
      - Systemic & Inflammatory Cardiovascular Diseases
      type: string
      description: |-
        * `heart diseases` - heart diseases
        * `vascular diseases` - vascular diseases
        * `Systemic & Inflammatory Cardiovascular Diseases` - Systemic & Inflammatory Cardiovascular Diseases
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
