# Generated by Django 5.1.6 on 2025-03-21 23:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdarticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
