# Generated by Django 5.1.6 on 2025-02-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="supra_category",
            new_name="sup_category",
        ),
    ]
