# Generated by Django 5.1.6 on 2025-02-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0003_rename_sup_category_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
