# Generated by Django 5.1.6 on 2025-02-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0004_article_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_highlighted",
            field=models.BooleanField(default=False),
        ),
    ]
