# Generated by Django 5.1.6 on 2025-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0005_article_is_highlighted"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_highlighted_score",
            field=models.IntegerField(default=0),
        ),
    ]
