# Generated by Django 5.1.6 on 2025-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0007_alter_article_is_highlighted_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(default="Abdelmoughit Fikri", max_length=50),
        ),
    ]
