# Generated by Django 5.1.6 on 2025-02-26 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0008_alter_article_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="cardiacDiseasesArticles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
