# Generated by Django 5.1.6 on 2025-02-26 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0009_alter_article_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                default="Abdelmoughit Fikri",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="cardiacDiseasesArticles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attachedfile",
            name="attached_file",
            field=models.FileField(
                blank=True, null=True, upload_to="cardiacDiseases/attached_files"
            ),
        ),
        migrations.AlterField(
            model_name="secondaryimage",
            name="secondary_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cardiacDiseases/secondary_images"
            ),
        ),
    ]
