# Generated by Django 5.1.6 on 2025-02-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0012_rename_author_article_author_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="author_id",
            new_name="author",
        ),
    ]
