# Generated by Django 5.1.6 on 2025-02-26 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiacDiseases", "0014_alter_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_highlighted_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
