# Generated by Django 5.1.6 on 2025-03-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0021_alter_cdarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdarticle',
            name='category',
            field=models.CharField(choices=[('heart diseases', 'heart diseases'), ('vascular diseases', 'vascular diseases'), ('systemic & Inflammatory Cardiovascular Diseases', 'systemic & Inflammatory Cardiovascular Diseases')], max_length=50),
        ),
    ]
