# Generated by Django 5.1.6 on 2025-03-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0022_alter_cdarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdarticle',
            name='category',
            field=models.CharField(choices=[('Heart diseases', 'heart diseases'), ('Vascular diseases', 'vascular diseases'), ('Systemic & Inflammatory Cardiovascular Diseases', 'systemic & Inflammatory Cardiovascular Diseases')], max_length=50),
        ),
    ]
