# Generated by Django 5.1.6 on 2025-03-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0023_alter_cdarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdarticle',
            name='category',
            field=models.CharField(choices=[('heart diseases', 'Heart diseases'), ('vascular diseases', 'Vascular diseases'), ('systemic & Inflammatory Cardiovascular Diseases', 'Systemic & Inflammatory Cardiovascular Diseases')], max_length=50),
        ),
    ]
