# Generated by Django 5.1.6 on 2025-03-20 20:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0025_alter_cdarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdarticle',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cdarticle',
            name='category',
            field=models.CharField(choices=[('heart diseases', 'heart diseases'), ('vascular diseases', 'vascular diseases'), ('systemic Diseases', 'systemic Diseases')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cdarticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='text'),
        ),
    ]
