# Generated by Django 5.1.6 on 2025-03-20 20:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0026_cdarticle_description_alter_cdarticle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdarticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
