# Generated by Django 5.1.6 on 2025-03-20 21:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0027_alter_cdarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterField(
            model_name='cdarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
