# Generated by Django 5.1.6 on 2025-03-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0028_myarticle_alter_cdarticle_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyArticle',
        ),
        migrations.AlterField(
            model_name='cdarticle',
            name='content',
            field=models.TextField(),
        ),
    ]
