# Generated by Django 5.1.6 on 2025-03-20 23:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacDiseases', '0029_delete_myarticle_alter_cdarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdarticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
