# Generated by Django 5.1.6 on 2025-03-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacInnovations', '0006_ciarticle_search_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciarticle',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
